Repository guberti/epschedule, pull requests merged in 2021-01, with the labels that each got.

#386 Change name of exceptions.json to master_schedule
  .github/workflows/deploy.yml
  data/exceptions.json
  data/master_schedule.json
  main.py
  scripts/date_schedules.py
  scripts/upload_master_schedule.py
Labels: cleanup, documentation

#393 Remove awful sign in bug
  main.py
Labels: bug, p0

#387 Add link to recrawl instructions to README
  README.md
Labels: documentation

#395 Rename references to exceptions.json in upload_master_schedule.py
  scripts/upload_exceptions.py
  scripts/upload_master_schedule.py
Labels: bug, p0

#388 Switch tests to use fake data and run entirely locally
  .gitignore
  README.md
  app.py
  data/test_api_keys.json
  data/test_crypto.key
  data/test_id_table.json
  data/test_schedules.json
  main.py
  main_test.py
  requirements.txt
Labels: cleanup, unit-tests
